<a href="https://colab.research.google.com/github/AMBogacz/data_driven_astronomy/blob/main/DDA_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Mean calculation

In [1]:
def calculate_mean(a):
  return sum(a) / len(a)

In [2]:
mean = calculate_mean([1,2.2,0.3,3.4,7.9])
mean

2.96

In [3]:
from statistics import mean

In [4]:
fluxes = [23.3, 42.1, 2.0, -3.2, 55.6]
m = mean(fluxes)
m

23.96

Add NumPy to speed up calculations

In [2]:
import numpy as np

In [6]:
np_fluxes = np.array(fluxes)
m = np.mean(np_fluxes)
m

23.96

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [4]:
print(a*2)

[2 4 6]


In [5]:
a + b

array([5, 7, 9])

In [6]:
a * b

array([ 4, 10, 18])

In [11]:
csv_data = [8.84,17.22,13.22,3.84,3.99,11.73,19.66,1.27,16.14,18.72,7.43,11.09]

In [12]:
data = np.array(csv_data)

In [13]:
np.around(np.mean(data), decimals=1)

11.1

In [14]:
np.around(np.median(data), decimals=1)

11.4